### ISSUE TITLE
Is it possible to run headless without node-webkit?

### ISSUE THREAD

**Issue by ViktorNova** [charlieroberts/interface.server#4]
I need to run Interface.Server on a headless system, so without node-webkit, and to instead access the server page from a browser on the LAN like a regular node app. Can Interface.Server be easily made to run without node-webkit like this, or would that be an epic undertaking? 

I know there are various ways get node-webkit to run on headless server using xvfb, but it would be ideal to not have the extra overhead if possible

**Comment by charlieroberts** [comment]
Hmmm. It would take some work. Unfortunately the server is in "waiting to be refactored" mode, so it's not very easy to change the code around at the moment.

It might be easier to add bi-directional communication to the Interface.js simpleserver script. Do you need to have multiple clients connected simultaneously? Or will your app generally be used by one user at a time? More specifically, would you need to send bi-directional messages to specific clients as opposed to sending them to all clients at once?

I'm not opposed to adding some of this into the simpleserver script. I don't want to replicate all the work, but at the same time I understand the need to not use nw.

**Comment by ViktorNova** [comment]
Oh man, that would be absolutely perfect. Bi-directional with the built-in simple server would make Interface a great deal more portable and easy to integrate into different things, I think that's an awesome idea

For my project there will be multiple clients, but bidirectional commutation will happen between the server and all connected clients at all times. I'm hoping that means I might be in luck? =D

**Comment by nonebutcarlo** [comment]
Hallo Charlie,

I wonder if you could still integrate bi-directional communication in interface.js.
In this way it would be easier to add your widgets into other works, as I'm trying to do.
I think it will be enough to receive Osc/Midi messages from one port and redirect to one client at a time.

And also because, due to my ignorance, I'm not able to build and let work Interface.server GUI on my 10.9/10.10 OS X system. (I have problem with refreshing nw windows, I think).

Anyway thanks for your job, it's really inspiring. 

Carlo.

**Comment by charlieroberts** [comment]
OK, I just did this. Make sure to read the readme in the server directory of the interface.js repo, and check out the OSC_test.htm example. Please open up any issues with the simpleserver in the interface.js repo, not here. Thanks!

**Comment by ViktorNova** [comment]
Awesome! I can't wait to try it out =D
